import Foundation

/// Static example sentences for vocabulary flashcards, keyed by verb ID.
struct VerbExamples {
    struct Example {
        let spanish: String
        let english: String
        var tense: Tense = .presente
    }

    static let sentences: [String: Example] = [
        "ser":        Example(spanish: "Soy estudiante de español.", english: "I am a Spanish student."),
        "estar":      Example(spanish: "Ella está en casa.", english: "She is at home."),
        "haber":      Example(spanish: "Ha llovido mucho hoy.", english: "It has rained a lot today."),
        "tener":      Example(spanish: "Nosotros tenemos un perro.", english: "We have a dog."),
        "hacer":      Example(spanish: "¿Qué haces los fines de semana?", english: "What do you do on weekends?"),
        "poder":      Example(spanish: "Puedo hablar español un poco.", english: "I can speak a little Spanish."),
        "decir":      Example(spanish: "Él siempre dice la verdad.", english: "He always tells the truth."),
        "ir":         Example(spanish: "Voy al mercado cada mañana.", english: "I go to the market every morning."),
        "ver":        Example(spanish: "Vemos una película esta noche.", english: "We are watching a movie tonight."),
        "dar":        Example(spanish: "Te doy el libro mañana.", english: "I will give you the book tomorrow."),
        "saber":      Example(spanish: "Ella sabe cocinar muy bien.", english: "She knows how to cook very well."),
        "querer":     Example(spanish: "Quiero aprender español.", english: "I want to learn Spanish."),
        "llegar":     Example(spanish: "El tren llega a las tres.", english: "The train arrives at three."),
        "pasar":      Example(spanish: "¿Qué pasó ayer?", english: "What happened yesterday?"),
        "deber":      Example(spanish: "Debes estudiar más.", english: "You should study more."),
        "poner":      Example(spanish: "Pongo la mesa para cenar.", english: "I set the table for dinner."),
        "parecer":    Example(spanish: "Parece que va a llover.", english: "It looks like it is going to rain."),
        "quedar":     Example(spanish: "Nos quedamos en el hotel.", english: "We stayed at the hotel."),
        "creer":      Example(spanish: "Creo que tienes razón.", english: "I think you are right."),
        "hablar":     Example(spanish: "Ellos hablan español en casa.", english: "They speak Spanish at home."),
        "llevar":     Example(spanish: "Llevo esta camisa todos los días.", english: "I wear this shirt every day."),
        "dejar":      Example(spanish: "Dejé mis llaves en la mesa.", english: "I left my keys on the table."),
        "seguir":     Example(spanish: "Sigue recto por esta calle.", english: "Keep going straight down this street."),
        "encontrar":  Example(spanish: "Encontré mi libro perdido.", english: "I found my lost book."),
        "llamar":     Example(spanish: "Te llamo esta tarde.", english: "I will call you this afternoon."),
        "venir":      Example(spanish: "¿De dónde vienes?", english: "Where do you come from?"),
        "pensar":     Example(spanish: "Pienso en ti todo el tiempo.", english: "I think about you all the time."),
        "salir":      Example(spanish: "Salgo a trabajar a las ocho.", english: "I leave for work at eight."),
        "volver":     Example(spanish: "Vuelvo a casa a las seis.", english: "I return home at six."),
        "tomar":      Example(spanish: "Tomo café con leche cada mañana.", english: "I drink coffee with milk every morning."),
        "conocer":    Example(spanish: "Conozco a mucha gente en Quito.", english: "I know many people in Quito."),
        "vivir":      Example(spanish: "Vivo en Ecuador desde niño.", english: "I have lived in Ecuador since I was a child."),
        "sentir":     Example(spanish: "Siento mucho frío en las mañanas.", english: "I feel very cold in the mornings."),
        "tratar":     Example(spanish: "Siempre trato de ser amable.", english: "I always try to be kind."),
        "mirar":      Example(spanish: "Miramos las estrellas por la noche.", english: "We look at the stars at night."),
        "contar":     Example(spanish: "Mi abuela cuenta historias increíbles.", english: "My grandmother tells amazing stories."),
        "empezar":    Example(spanish: "La clase empieza a las nueve.", english: "Class starts at nine."),
        "esperar":    Example(spanish: "Espero el autobús en la parada.", english: "I wait for the bus at the stop."),
        "buscar":     Example(spanish: "Busco trabajo en la ciudad.", english: "I am looking for work in the city."),
        "entrar":     Example(spanish: "Entramos al museo juntos.", english: "We entered the museum together."),
        "trabajar":   Example(spanish: "Trabajo en una oficina pequeña.", english: "I work in a small office."),
        "escribir":   Example(spanish: "Escribo cartas a mis amigos.", english: "I write letters to my friends."),
        "perder":     Example(spanish: "Perdí mi billetera esta mañana.", english: "I lost my wallet this morning."),
        "producir":   Example(spanish: "Ecuador produce las mejores rosas.", english: "Ecuador produces the best roses."),
        "ocurrir":    Example(spanish: "El accidente ocurrió de repente.", english: "The accident happened suddenly."),
        "entender":   Example(spanish: "No entiendo esta pregunta.", english: "I don't understand this question."),
        "pedir":      Example(spanish: "Pido ayuda cuando la necesito.", english: "I ask for help when I need it."),
        "recibir":    Example(spanish: "Recibí una carta de mi familia.", english: "I received a letter from my family."),
        "recordar":   Example(spanish: "Recuerdo mi primer día de escuela.", english: "I remember my first day of school."),
        "terminar":   Example(spanish: "Termino el trabajo a las cinco.", english: "I finish work at five."),
        "permitir":   Example(spanish: "No se permite fumar aquí.", english: "Smoking is not permitted here."),
        "aparecer":   Example(spanish: "El sol apareció tras las nubes.", english: "The sun appeared from behind the clouds."),
        "conseguir":  Example(spanish: "Conseguí el trabajo que quería.", english: "I got the job I wanted."),
        "comenzar":   Example(spanish: "El concierto comienza a las ocho.", english: "The concert begins at eight."),
        "servir":     Example(spanish: "Este restaurante sirve comida deliciosa.", english: "This restaurant serves delicious food."),
        "sacar":      Example(spanish: "Saca las fotos con tu celular.", english: "Take the photos with your phone."),
        "necesitar":  Example(spanish: "Necesito más tiempo para pensar.", english: "I need more time to think."),
        "mantener":   Example(spanish: "Mantengo mi habitación ordenada.", english: "I keep my room tidy."),
        "resultar":   Example(spanish: "Resultó ser más fácil de lo esperado.", english: "It turned out to be easier than expected."),
        "leer":       Example(spanish: "Leo un libro antes de dormir.", english: "I read a book before sleeping."),
        "caer":       Example(spanish: "Las hojas caen en el otoño.", english: "The leaves fall in autumn."),
        "cambiar":    Example(spanish: "Cambio de opinión a veces.", english: "I change my mind sometimes."),
        "presentar":  Example(spanish: "El profesor presentó el tema nuevo.", english: "The teacher introduced the new topic."),
        "crear":      Example(spanish: "Creo arte en mi tiempo libre.", english: "I create art in my free time."),
        "abrir":      Example(spanish: "Abre la ventana, por favor.", english: "Open the window, please."),
        "acabar":     Example(spanish: "Acabo de llegar a casa.", english: "I have just arrived home."),
        "convertir":  Example(spanish: "La oruga se convierte en mariposa.", english: "The caterpillar turns into a butterfly."),
        "ganar":      Example(spanish: "Nuestro equipo ganó el partido.", english: "Our team won the match."),
        "formar":     Example(spanish: "Formamos un grupo de estudio.", english: "We formed a study group."),
        "traer":      Example(spanish: "Trae tu paraguas, va a llover.", english: "Bring your umbrella, it is going to rain."),
        "partir":     Example(spanish: "El tren parte a las siete.", english: "The train departs at seven."),
        "morir":      Example(spanish: "Las flores mueren sin agua.", english: "Flowers die without water."),
        "aceptar":    Example(spanish: "Acepto tu invitación con gusto.", english: "I gladly accept your invitation."),
        "realizar":   Example(spanish: "Realizo mis sueños paso a paso.", english: "I achieve my dreams step by step."),
        "suponer":    Example(spanish: "Supongo que tienes razón.", english: "I suppose you are right."),
        "comprender": Example(spanish: "Comprendo mejor con ejemplos.", english: "I understand better with examples."),
        "lograr":     Example(spanish: "Logró terminar el maratón.", english: "He managed to finish the marathon."),
        "explicar":   Example(spanish: "El maestro explica la lección.", english: "The teacher explains the lesson."),
        "preguntar":  Example(spanish: "Pregunto cuando no entiendo algo.", english: "I ask when I don't understand something."),
        "tocar":      Example(spanish: "Toco la guitarra los domingos.", english: "I play the guitar on Sundays."),
        "reconocer":  Example(spanish: "Reconozco tu voz en seguida.", english: "I recognize your voice right away."),
        "estudiar":   Example(spanish: "Estudio español todos los días.", english: "I study Spanish every day."),
        "alcanzar":   Example(spanish: "Alcanzamos la cima de la montaña.", english: "We reached the top of the mountain."),
        "nacer":      Example(spanish: "Nací en Quito en primavera.", english: "I was born in Quito in spring."),
        "dirigir":    Example(spanish: "Dirige la orquesta con pasión.", english: "He conducts the orchestra with passion."),
        "correr":     Example(spanish: "Corro cinco kilómetros cada mañana.", english: "I run five kilometers every morning."),
        "utilizar":   Example(spanish: "Utilizo el diccionario cuando es necesario.", english: "I use the dictionary when necessary."),
        "pagar":      Example(spanish: "Pago las cuentas a tiempo.", english: "I pay the bills on time."),
        "dormir":     Example(spanish: "Duermo ocho horas cada noche.", english: "I sleep eight hours every night."),
        "comer":      Example(spanish: "Comemos juntos a las dos.", english: "We eat together at two."),
        "beber":      Example(spanish: "Bebo agua después de hacer ejercicio.", english: "I drink water after exercising."),
        "aprender":   Example(spanish: "Aprendo algo nuevo cada día.", english: "I learn something new every day."),
        "jugar":      Example(spanish: "Juego fútbol con mis amigos.", english: "I play soccer with my friends."),
        "caminar":    Example(spanish: "Camino al trabajo todos los días.", english: "I walk to work every day."),
        "ofrecer":      Example(spanish: "El restaurante ofrece un menú especial.", english: "The restaurant offers a special menu."),
        "incluir":      Example(spanish: "El precio incluye el desayuno.", english: "The price includes breakfast."),
        "usar":         Example(spanish: "Uso el transporte público cada día.", english: "I use public transportation every day."),
        "unir":         Example(spanish: "Este proyecto une a toda la familia.", english: "This project brings the whole family together."),
        "existir":      Example(spanish: "Existen muchas oportunidades en esta ciudad.", english: "There are many opportunities in this city."),
        "considerar":   Example(spanish: "Considera todas las opciones antes de decidir.", english: "Consider all the options before deciding."),
        "mostrar":      Example(spanish: "Te muestro el camino al centro.", english: "I will show you the way to the center."),
        "ayudar":       Example(spanish: "Mi vecino me ayuda con las compras.", english: "My neighbor helps me with the shopping."),
        "desarrollar":  Example(spanish: "Desarrollamos un plan para el proyecto.", english: "We developed a plan for the project."),
        "obtener":      Example(spanish: "Obtuve mi pasaporte la semana pasada.", english: "I got my passport last week."),
        "gustar":       Example(spanish: "Me gusta mucho la música en vivo.", english: "I really like live music."),
        "destacar":     Example(spanish: "Ella destaca en matemáticas.", english: "She stands out in mathematics."),
        "publicar":     Example(spanish: "Publicó su primer libro este año.", english: "He published his first book this year."),
        "establecer":   Example(spanish: "Establecemos reglas claras en casa.", english: "We establish clear rules at home."),
        "generar":      Example(spanish: "El turismo genera muchos empleos.", english: "Tourism generates many jobs."),
        "asegurar":     Example(spanish: "Asegura la puerta antes de salir.", english: "Lock the door before you leave."),
        "cumplir":      Example(spanish: "Siempre cumplo mis promesas.", english: "I always keep my promises."),
        "compartir":    Example(spanish: "Compartimos el apartamento con dos amigos.", english: "We share the apartment with two friends."),
        "pesar":        Example(spanish: "La maleta pesa demasiado para el vuelo.", english: "The suitcase is too heavy for the flight."),
        "indicar":      Example(spanish: "El mapa indica la ruta más corta.", english: "The map shows the shortest route."),
        "comprar":      Example(spanish: "Compro frutas frescas en el mercado.", english: "I buy fresh fruit at the market."),
        "señalar":      Example(spanish: "El guía señaló los puntos de interés.", english: "The guide pointed out the places of interest."),
        "decidir":      Example(spanish: "Decidí quedarme en casa esta noche.", english: "I decided to stay home tonight."),
        "evitar":       Example(spanish: "Evito el tráfico saliendo temprano.", english: "I avoid traffic by leaving early."),
        "participar":   Example(spanish: "Participamos en el concurso de cocina.", english: "We participated in the cooking contest."),
        "mejorar":      Example(spanish: "Mi español mejora cada semana.", english: "My Spanish improves every week."),
        "elegir":       Example(spanish: "Elige el color que más te guste.", english: "Choose the color you like best."),
        "disfrutar":    Example(spanish: "Disfruto caminando por la playa.", english: "I enjoy walking on the beach."),
        "aplicar":      Example(spanish: "Aplica la crema dos veces al día.", english: "Apply the cream twice a day."),
        "intentar":     Example(spanish: "Intento hablar español con mis vecinos.", english: "I try to speak Spanish with my neighbors."),
        "disponer":     Example(spanish: "Disponemos de poco tiempo hoy.", english: "We have little time available today."),
        "determinar":   Example(spanish: "El médico determinó la causa del problema.", english: "The doctor determined the cause of the problem."),
        "continuar":    Example(spanish: "Continúa recto hasta el semáforo.", english: "Continue straight until the traffic light."),
        "relacionar":   Example(spanish: "Relaciono las palabras con imágenes.", english: "I associate words with images."),
        "afectar":      Example(spanish: "El frío afecta mi estado de ánimo.", english: "The cold affects my mood."),
        "informar":     Example(spanish: "Te informo de los cambios por correo.", english: "I will inform you of the changes by email."),
        "acercar":      Example(spanish: "Me acerco a la ventana para ver mejor.", english: "I move closer to the window to see better."),
        "requerir":     Example(spanish: "Este trabajo requiere mucha concentración.", english: "This job requires a lot of concentration."),
        "reducir":      Example(spanish: "Reduzco el consumo de azúcar.", english: "I am reducing my sugar intake."),
        "preparar":     Example(spanish: "Preparo la cena antes de que llegues.", english: "I will prepare dinner before you arrive."),
        "enviar":       Example(spanish: "Envié un correo a mi jefe.", english: "I sent an email to my boss."),
        "construir":    Example(spanish: "Construyen una nueva escuela en el barrio.", english: "They are building a new school in the neighborhood."),
        "representar":  Example(spanish: "Este trofeo representa nuestro esfuerzo.", english: "This trophy represents our effort."),
        "dedicar":      Example(spanish: "Dedico dos horas al día a leer.", english: "I dedicate two hours a day to reading."),
        "cerrar":       Example(spanish: "Cierra la ventana, hace frío.", english: "Close the window, it is cold."),
        "iniciar":      Example(spanish: "Iniciamos el proyecto la próxima semana.", english: "We start the project next week."),
        "aumentar":     Example(spanish: "Los precios aumentaron este mes.", english: "Prices went up this month."),
        "desear":       Example(spanish: "Deseo que tengas un buen viaje.", english: "I wish you a good trip."),
        "añadir":       Example(spanish: "Añade un poco de sal a la sopa.", english: "Add a little salt to the soup."),
        "funcionar":    Example(spanish: "Mi computadora no funciona bien hoy.", english: "My computer is not working well today."),
        "privar":       Example(spanish: "El ruido me priva del sueño.", english: "The noise deprives me of sleep."),
        "celebrar":     Example(spanish: "Celebramos el cumpleaños con pastel.", english: "We celebrated the birthday with cake."),
        "referir":      Example(spanish: "Me refiero a lo que dijiste ayer.", english: "I am referring to what you said yesterday."),
        "basar":        Example(spanish: "La decisión se basa en los datos.", english: "The decision is based on the data."),
        "acompañar":    Example(spanish: "Te acompaño al médico mañana.", english: "I will go with you to the doctor tomorrow."),
        "organizar":    Example(spanish: "Organizo mi escritorio cada lunes.", english: "I organize my desk every Monday."),
        "escuchar":     Example(spanish: "Escucho música mientras cocino.", english: "I listen to music while I cook."),
        "descubrir":    Example(spanish: "Descubrí un restaurante nuevo increíble.", english: "I discovered an amazing new restaurant."),
        "demostrar":    Example(spanish: "El estudiante demostró sus habilidades.", english: "The student demonstrated his skills."),
        "solicitar":    Example(spanish: "Solicité una beca para estudiar.", english: "I applied for a scholarship to study."),
        "ubicar":       Example(spanish: "El hotel está ubicado en el centro.", english: "The hotel is located in the center."),
        "sufrir":       Example(spanish: "Sufro de alergias en primavera.", english: "I suffer from allergies in spring."),
        "soler":        Example(spanish: "Suelo desayunar temprano.", english: "I usually have breakfast early."),
        "vender":       Example(spanish: "Venden ropa de segunda mano aquí.", english: "They sell secondhand clothes here."),
        "responder":    Example(spanish: "Respondió todas las preguntas del examen.", english: "She answered all the exam questions."),
        "afirmar":      Example(spanish: "Afirma que llegará puntual.", english: "He claims he will arrive on time."),
        "recomendar":   Example(spanish: "Te recomiendo este libro.", english: "I recommend this book to you."),
        "visitar":      Example(spanish: "Visitamos a los abuelos los domingos.", english: "We visit the grandparents on Sundays."),
        "proponer":     Example(spanish: "Propongo que salgamos a cenar.", english: "I propose that we go out for dinner."),
        "adecuar":      Example(spanish: "Adecuamos el espacio para trabajar.", english: "We adapted the space for working."),
        "mencionar":    Example(spanish: "Mencionó tu nombre en la reunión.", english: "She mentioned your name in the meeting."),
        "marcar":       Example(spanish: "Marca el número de teléfono con cuidado.", english: "Dial the phone number carefully."),
        "registrar":    Example(spanish: "Registra tu entrada en la recepción.", english: "Register your arrival at the reception desk."),
        "entregar":     Example(spanish: "Entrego el informe el viernes.", english: "I will hand in the report on Friday."),
        "definir":      Example(spanish: "El diccionario define las palabras.", english: "The dictionary defines words."),
        "sumar":        Example(spanish: "Suma los gastos del mes.", english: "Add up the expenses for the month."),
        "subir":        Example(spanish: "Subimos las escaleras hasta el tercer piso.", english: "We climbed the stairs to the third floor."),
        "avanzar":      Example(spanish: "Avanzamos rápido en el proyecto.", english: "We are making quick progress on the project."),
        "observar":     Example(spanish: "Observo las aves desde mi ventana.", english: "I watch the birds from my window."),
        "comentar":     Example(spanish: "Comentó que la película fue excelente.", english: "He commented that the film was excellent."),
        "significar":   Example(spanish: "¿Qué significa esta palabra en español?", english: "What does this word mean in Spanish?"),
        "analizar":     Example(spanish: "Analizamos los resultados del examen.", english: "We analyzed the exam results."),
        "expresar":     Example(spanish: "Expresa tus sentimientos con claridad.", english: "Express your feelings clearly."),
        "integrar":     Example(spanish: "Integra el ejercicio en tu rutina diaria.", english: "Integrate exercise into your daily routine."),
        "crecer":       Example(spanish: "El niño creció mucho este verano.", english: "The child grew a lot this summer."),
        "contener":     Example(spanish: "Este jugo contiene mucha vitamina C.", english: "This juice contains a lot of vitamin C."),
        "interesar":    Example(spanish: "Me interesa aprender sobre culturas nuevas.", english: "I am interested in learning about new cultures."),
        "colocar":      Example(spanish: "Coloca las flores en el jarrón.", english: "Place the flowers in the vase."),
        "anunciar":     Example(spanish: "Anunciaron los resultados por la tarde.", english: "They announced the results in the afternoon."),
        "aportar":      Example(spanish: "Cada miembro aporta ideas al grupo.", english: "Each member contributes ideas to the group."),
        "superar":      Example(spanish: "Superó todos los obstáculos con esfuerzo.", english: "She overcame all the obstacles with effort."),
        "agregar":      Example(spanish: "Agrega más especias a la salsa.", english: "Add more spices to the sauce."),
        "apoyar":       Example(spanish: "Mi familia siempre me apoya.", english: "My family always supports me."),
        "garantizar":   Example(spanish: "Garantizamos la calidad de nuestros productos.", english: "We guarantee the quality of our products."),
        "sentar":       Example(spanish: "Me siento mejor después de descansar.", english: "I feel better after resting."),
        "ocupar":       Example(spanish: "Esta tarea me ocupa toda la mañana.", english: "This task takes up my whole morning."),
        "depender":     Example(spanish: "El plan depende del tiempo que haga.", english: "The plan depends on the weather."),
        "identificar":  Example(spanish: "Identificamos el problema rápidamente.", english: "We identified the problem quickly."),
        "aprovechar":   Example(spanish: "Aprovecho las rebajas para comprar ropa.", english: "I take advantage of the sales to buy clothes."),
        "proteger":     Example(spanish: "Usa protector solar para proteger tu piel.", english: "Use sunscreen to protect your skin."),
        "plantear":     Example(spanish: "Planteó una pregunta muy interesante.", english: "He raised a very interesting question."),
        "proporcionar": Example(spanish: "El gobierno proporciona ayuda a las familias.", english: "The government provides help to families."),
        "situar":       Example(spanish: "La novela se sitúa en el siglo XIX.", english: "The novel is set in the 19th century."),
        "lanzar":       Example(spanish: "Lanzaron un nuevo producto al mercado.", english: "They launched a new product on the market."),
        "provocar":     Example(spanish: "El accidente provocó un gran tráfico.", english: "The accident caused a major traffic jam."),
        "adquirir":     Example(spanish: "Adquirí nuevas habilidades en el curso.", english: "I acquired new skills in the course."),
        "cubrir":       Example(spanish: "Cubre la olla con una tapa.", english: "Cover the pot with a lid."),
        "diseñar":      Example(spanish: "Diseñó una aplicación para aprender idiomas.", english: "She designed an app for learning languages."),
        "resolver":     Example(spanish: "Resolvemos los problemas en equipo.", english: "We solve problems as a team."),
        "probar":       Example(spanish: "Prueba este plato, está delicioso.", english: "Try this dish, it is delicious."),
        "enfrentar":    Example(spanish: "Enfrentamos los desafíos con calma.", english: "We face challenges calmly."),
        "olvidar":      Example(spanish: "Olvidé llevar el paraguas.", english: "I forgot to bring my umbrella."),
        "confirmar":    Example(spanish: "Confirma tu reserva por teléfono.", english: "Confirm your reservation by phone."),
        "instalar":     Example(spanish: "Instalé una aplicación nueva en mi celular.", english: "I installed a new app on my phone."),
        "recuperar":    Example(spanish: "Me recuperé del resfriado en tres días.", english: "I recovered from the cold in three days."),
        "aprobar":      Example(spanish: "Aprobé el examen de conducir.", english: "I passed the driving test."),
        "declarar":     Example(spanish: "Declararon su amor frente a todos.", english: "They declared their love in front of everyone."),
        "actuar":       Example(spanish: "Ella actúa en el teatro los fines de semana.", english: "She acts in the theater on weekends."),
        "incorporar":   Example(spanish: "Incorporamos frutas a nuestro desayuno.", english: "We incorporated fruit into our breakfast."),
        "controlar":    Example(spanish: "Controlo mis gastos con una aplicación.", english: "I track my expenses with an app."),
        "atender":      Example(spanish: "El médico atiende a los pacientes con cuidado.", english: "The doctor attends to patients with care."),
        "faltar":       Example(spanish: "Faltan cinco minutos para la reunión.", english: "There are five minutes left until the meeting."),
        "obligar":      Example(spanish: "Nadie me obliga a hacer esto.", english: "Nobody is forcing me to do this."),
        "limitar":      Example(spanish: "Limitamos el tiempo de pantalla en casa.", english: "We limit screen time at home."),
        "constituir":   Example(spanish: "Esto constituye una falta grave.", english: "This constitutes a serious offense."),
        "corresponder": Example(spanish: "Me corresponde pagar esta vez.", english: "It is my turn to pay this time."),
        "adaptar":      Example(spanish: "Me adapto fácilmente a los cambios.", english: "I adapt easily to changes."),
        "eliminar":     Example(spanish: "Eliminé los archivos innecesarios.", english: "I deleted the unnecessary files."),
        "pretender":    Example(spanish: "Pretende que no escuchó nada.", english: "He pretends he did not hear anything."),
        "brindar":      Example(spanish: "Brindamos por el éxito del proyecto.", english: "We toasted to the success of the project."),
        "exponer":      Example(spanish: "Expuso sus ideas ante la clase.", english: "She presented her ideas to the class."),
        "prever":       Example(spanish: "Prevemos lluvias para el fin de semana.", english: "We expect rain for the weekend."),
        "encantar":     Example(spanish: "Me encanta el café por las mañanas.", english: "I love coffee in the mornings."),
        "conectar":     Example(spanish: "Conecto el teléfono al cargador.", english: "I connect my phone to the charger."),
        "sostener":     Example(spanish: "Sostiene que tiene razón.", english: "He maintains that he is right."),
        "acceder":      Example(spanish: "Accedo al sistema con mi contraseña.", english: "I access the system with my password."),
        "mover":        Example(spanish: "Mueve la mesa hacia la ventana.", english: "Move the table toward the window."),
        "facilitar":    Example(spanish: "Las apps facilitan el aprendizaje de idiomas.", english: "Apps make language learning easier."),
        "reunir":       Example(spanish: "Nos reunimos los viernes para cenar.", english: "We get together on Fridays for dinner."),
        "seleccionar":  Example(spanish: "Selecciona la respuesta correcta.", english: "Select the correct answer."),
        "defender":     Example(spanish: "Defiende sus opiniones con argumentos.", english: "She defends her opinions with arguments."),
        "bajar":        Example(spanish: "Bajo las escaleras con cuidado.", english: "I go down the stairs carefully."),
        "viajar":       Example(spanish: "Viajamos a la costa el próximo verano.", english: "We are traveling to the coast next summer."),
        "implicar":     Example(spanish: "Esto implica mucho trabajo.", english: "This implies a lot of work."),
        "recoger":      Example(spanish: "Recojo a los niños a las tres.", english: "I pick up the children at three."),
        "surgir":       Example(spanish: "Surgieron problemas durante el proyecto.", english: "Problems came up during the project."),
        "causar":       Example(spanish: "El estrés puede causar muchos problemas.", english: "Stress can cause many problems."),
        "elaborar":     Example(spanish: "Elaboramos un informe detallado.", english: "We put together a detailed report."),
        "poseer":       Example(spanish: "Posee una gran colección de libros.", english: "He owns a large book collection."),
        "invitar":      Example(spanish: "Te invito a cenar el sábado.", english: "I am inviting you to dinner on Saturday."),
        "elevar":       Example(spanish: "El ejercicio eleva tu nivel de energía.", english: "Exercise raises your energy level."),
        "exigir":       Example(spanish: "El trabajo exige mucha dedicación.", english: "The job demands a lot of dedication."),
        "consultar":    Example(spanish: "Consulto al médico cuando estoy enfermo.", english: "I see the doctor when I am sick."),
        "detener":      Example(spanish: "La policía detuvo el vehículo.", english: "The police stopped the vehicle."),
        "asociar":      Example(spanish: "Asocio los colores con las emociones.", english: "I associate colors with emotions."),
        "manifestar":   Example(spanish: "Manifestó su desacuerdo con calma.", english: "She expressed her disagreement calmly."),
        "cuidar":       Example(spanish: "Cuido a mi abuela los fines de semana.", english: "I take care of my grandmother on weekends."),
        "valer":        Example(spanish: "¿Cuánto vale este libro?", english: "How much does this book cost?"),
        "describir":    Example(spanish: "Describe la ciudad donde vives.", english: "Describe the city where you live."),
        "apuntar":      Example(spanish: "Apunta la dirección en tu teléfono.", english: "Write down the address in your phone."),
        "promover":     Example(spanish: "Promovemos el turismo local.", english: "We promote local tourism."),
        "encargar":     Example(spanish: "Me encargué de organizar la reunión.", english: "I took charge of organizing the meeting."),
        "importar":     Example(spanish: "No me importa el frío cuando viajo.", english: "I do not mind the cold when I travel."),
        "asumir":       Example(spanish: "Asumo la responsabilidad del error.", english: "I take responsibility for the mistake."),
        "meter":        Example(spanish: "Mete los documentos en la carpeta.", english: "Put the documents in the folder."),
        "costar":       Example(spanish: "Este vuelo cuesta demasiado.", english: "This flight costs too much."),
        "levantar":     Example(spanish: "Me levanto a las seis cada mañana.", english: "I get up at six every morning."),
        "echar":        Example(spanish: "Echo sal a las papas fritas.", english: "I put salt on the french fries."),
        "agradecer":    Example(spanish: "Agradezco tu ayuda de corazón.", english: "I sincerely thank you for your help."),
        "imponer":      Example(spanish: "Imponen multas a quien no respeta las normas.", english: "They impose fines on those who break the rules."),
        "armar":        Example(spanish: "Armamos la tienda de campaña en media hora.", english: "We set up the tent in half an hour."),
        "componer":     Example(spanish: "Compuso una canción para su madre.", english: "He composed a song for his mother."),
        "repetir":      Example(spanish: "Repite la frase hasta aprenderla.", english: "Repeat the phrase until you learn it."),
        "romper":       Example(spanish: "Se me rompió el vaso sin querer.", english: "I accidentally broke the glass."),
        "citar":        Example(spanish: "El profesor citó a un filósofo famoso.", english: "The teacher quoted a famous philosopher."),
        "centrar":      Example(spanish: "Me centro en una tarea a la vez.", english: "I focus on one task at a time."),
        "guardar":      Example(spanish: "Guarda los documentos en una carpeta segura.", english: "Keep the documents in a safe folder."),
        "destinar":     Example(spanish: "Destinamos fondos para la educación.", english: "We set aside funds for education."),
        "firmar":       Example(spanish: "Firmé el contrato esta mañana.", english: "I signed the contract this morning."),
        "especializar": Example(spanish: "Se especializó en medicina infantil.", english: "She specialized in pediatric medicine."),
        "enseñar":      Example(spanish: "Mi madre me enseñó a cocinar.", english: "My mother taught me how to cook."),
        "otorgar":      Example(spanish: "Le otorgaron el premio al mejor estudiante.", english: "They awarded the prize to the best student."),
        "preferir":     Example(spanish: "Prefiero el té al café.", english: "I prefer tea to coffee."),
        "concluir":     Example(spanish: "Concluimos la reunión a tiempo.", english: "We concluded the meeting on time."),
        "asistir":      Example(spanish: "Asisto a clase todos los días.", english: "I attend class every day."),
        "denominar":    Example(spanish: "Esta técnica se denomina aprendizaje activo.", english: "This technique is called active learning."),
        "separar":      Example(spanish: "Separamos la basura para reciclar.", english: "We separate the trash for recycling."),
        "contribuir":   Example(spanish: "Cada uno contribuye con su talento.", english: "Everyone contributes with their talent."),
        "conducir":     Example(spanish: "Conduzco con cuidado en la lluvia.", english: "I drive carefully in the rain."),
        "combinar":     Example(spanish: "Combina colores para decorar tu cuarto.", english: "Combine colors to decorate your room."),
        "quitar":       Example(spanish: "Quita los zapatos antes de entrar.", english: "Take off your shoes before entering."),
        "preocupar":    Example(spanish: "Me preocupa no llegar a tiempo.", english: "I am worried about not arriving on time."),
        "finalizar":    Example(spanish: "Finalizamos el curso con éxito.", english: "We successfully finished the course."),
        "comunicar":    Example(spanish: "Comunico mis ideas con claridad.", english: "I communicate my ideas clearly."),
        "impulsar":     Example(spanish: "Impulsamos el desarrollo de nuevas tecnologías.", english: "We drive the development of new technologies."),
        "abandonar":    Example(spanish: "No abandones tus sueños nunca.", english: "Never abandon your dreams."),
        "imaginar":     Example(spanish: "Imagina un mundo sin contaminación.", english: "Imagine a world without pollution."),
        "modificar":    Example(spanish: "Modificamos el plan según las circunstancias.", english: "We modified the plan according to the circumstances."),
        "ingresar":     Example(spanish: "Ingresé a la universidad hace dos años.", english: "I started university two years ago."),
        "caber":        Example(spanish: "No caben todos en el ascensor.", english: "Not everyone fits in the elevator."),
        "animar":       Example(spanish: "Los aficionados animan al equipo.", english: "The fans cheer on the team."),
        "emitir":       Example(spanish: "La radio emite noticias cada hora.", english: "The radio broadcasts news every hour."),
        "regresar":     Example(spanish: "Regresé a casa muy tarde.", english: "I got back home very late."),
        "extender":     Example(spanish: "Extiende la mantequilla sobre el pan.", english: "Spread the butter on the bread."),
        "acudir":       Example(spanish: "Acudo al dentista dos veces al año.", english: "I go to the dentist twice a year."),
        "consistir":    Example(spanish: "La receta consiste en tres pasos simples.", english: "The recipe consists of three simple steps."),
        "andar":        Example(spanish: "Andamos por el parque después de comer.", english: "We walk through the park after eating."),
        "emplear":      Example(spanish: "La empresa emplea a cien personas.", english: "The company employs a hundred people."),
        "completar":    Example(spanish: "Completa el formulario con tus datos.", english: "Fill in the form with your details."),
        "prestar":      Example(spanish: "Te presto mi paraguas si quieres.", english: "I will lend you my umbrella if you want."),
        "introducir":   Example(spanish: "Introduce la tarjeta en el cajero.", english: "Insert the card into the ATM."),
        "permanecer":   Example(spanish: "Permanecimos en silencio durante la ceremonia.", english: "We remained silent during the ceremony."),
        "valorar":      Example(spanish: "Valoro mucho tu honestidad.", english: "I really value your honesty."),
        "merecer":      Example(spanish: "Mereces un descanso después de tanto trabajo.", english: "You deserve a break after so much work."),
        "revelar":      Example(spanish: "Reveló el secreto sin querer.", english: "She accidentally revealed the secret."),
        "cobrar":       Example(spanish: "Cobro mi sueldo los últimos días del mes.", english: "I collect my salary at the end of the month."),
        "variar":       Example(spanish: "Los precios varían según la temporada.", english: "Prices vary depending on the season."),
        "revisar":      Example(spanish: "Revisa el correo antes de enviarlo.", english: "Check the email before sending it."),
        "notar":        Example(spanish: "Noté que algo había cambiado.", english: "I noticed that something had changed."),
        "evaluar":      Example(spanish: "El profesor evalúa el trabajo de los estudiantes.", english: "The teacher evaluates the students' work."),
        "conformar":    Example(spanish: "No me conformo con resultados mediocres.", english: "I do not settle for mediocre results."),
        "divertir":     Example(spanish: "Los juegos de mesa me divierten mucho.", english: "Board games are a lot of fun for me."),
        "estimar":      Example(spanish: "Estimamos que el viaje dura dos horas.", english: "We estimate the trip takes two hours."),
        "pertenecer":   Example(spanish: "Este libro pertenece a la biblioteca.", english: "This book belongs to the library."),
        "negar":        Example(spanish: "Negó haber estado allí.", english: "He denied having been there."),
        "desaparecer":  Example(spanish: "Las nubes desaparecieron por la tarde.", english: "The clouds disappeared in the afternoon."),
        "actualizar":   Example(spanish: "Actualiza tu contraseña con regularidad.", english: "Update your password regularly."),
        "sorprender":   Example(spanish: "Me sorprendió encontrarte aquí.", english: "I was surprised to find you here."),
        "complicar":    Example(spanish: "No compliques más las cosas.", english: "Do not make things more complicated."),
        "trasladar":    Example(spanish: "Me trasladé a otra ciudad por trabajo.", english: "I moved to another city for work."),
        "fijar":        Example(spanish: "Fijamos la fecha para la reunión.", english: "We set the date for the meeting."),
        "comprobar":    Example(spanish: "Comprueba que tienes todos los documentos.", english: "Check that you have all the documents."),
        "retirar":      Example(spanish: "Retiré dinero del cajero automático.", english: "I withdrew money from the ATM."),
        "ampliar":      Example(spanish: "Ampliamos el plazo de entrega.", english: "We extended the deadline."),
        "ordenar":      Example(spanish: "Ordena tu habitación antes de salir.", english: "Tidy up your room before you leave."),
        "recorrer":     Example(spanish: "Recorremos la ciudad a pie.", english: "We explore the city on foot."),
        "denunciar":    Example(spanish: "Denunció el robo a la policía.", english: "She reported the theft to the police."),
        "ejecutar":     Example(spanish: "Ejecutamos el plan sin problemas.", english: "We carried out the plan without problems."),
        "impedir":      Example(spanish: "La lluvia impidió el partido.", english: "The rain prevented the match."),
        "medir":        Example(spanish: "Mide los ingredientes antes de cocinar.", english: "Measure the ingredients before cooking."),
        "amar":         Example(spanish: "Amo a mi familia sobre todas las cosas.", english: "I love my family above all things."),
        "operar":       Example(spanish: "El cirujano operó al paciente con éxito.", english: "The surgeon operated on the patient successfully."),
        "ejercer":      Example(spanish: "Ejerce su profesión con mucho orgullo.", english: "She practices her profession with great pride."),
        "detectar":     Example(spanish: "El médico detectó el problema a tiempo.", english: "The doctor detected the problem in time."),
        "transformar":  Example(spanish: "El viaje me transformó por completo.", english: "The trip completely transformed me."),
        "matar":        Example(spanish: "El frío mata las plantas tropicales.", english: "The cold kills tropical plants."),
        "interpretar":  Example(spanish: "Interpreta el papel principal en la obra.", english: "She plays the lead role in the play."),
        "practicar":    Example(spanish: "Practico español cada día.", english: "I practice Spanish every day."),
        "vincular":     Example(spanish: "Vinculamos el trabajo con el aprendizaje.", english: "We link work with learning."),
        "transmitir":   Example(spanish: "El canal transmite partidos en vivo.", english: "The channel broadcasts matches live."),
        "adoptar":      Example(spanish: "Adoptamos un perro del refugio.", english: "We adopted a dog from the shelter."),
        "invertir":     Example(spanish: "Invierte en tu educación.", english: "Invest in your education."),
        "fabricar":     Example(spanish: "Fabrican zapatos de cuero artesanal.", english: "They make handcrafted leather shoes."),
        "reflejar":     Example(spanish: "Sus palabras reflejan su personalidad.", english: "His words reflect his personality."),
        "mandar":       Example(spanish: "Manda un mensaje cuando llegues.", english: "Send a message when you arrive."),
        "abordar":      Example(spanish: "Abordamos el tema con cuidado.", english: "We approached the topic carefully."),
        "vestir":       Example(spanish: "Viste ropa cómoda para el viaje.", english: "Wear comfortable clothes for the trip."),
        "experimentar": Example(spanish: "Experimentamos cambios grandes este año.", english: "We experienced major changes this year."),
        "luchar":       Example(spanish: "Lucha por tus derechos sin miedo.", english: "Fight for your rights without fear."),
        "cargar":       Example(spanish: "Cargo mi teléfono durante la noche.", english: "I charge my phone overnight."),
        "contratar":    Example(spanish: "La empresa contrató a nuevos empleados.", english: "The company hired new employees."),
        "comparar":     Example(spanish: "Comparé los precios antes de comprar.", english: "I compared prices before buying."),
        "proceder":     Example(spanish: "Procedemos a revisar los documentos.", english: "We proceed to review the documents."),
        "comprometer":  Example(spanish: "Me comprometo a entregar el trabajo a tiempo.", english: "I commit to delivering the work on time."),
        "cortar":       Example(spanish: "Corta el pan en rebanadas.", english: "Cut the bread into slices."),
        "manejar":      Example(spanish: "Manejo situaciones difíciles con calma.", english: "I handle difficult situations calmly."),
        "descargar":    Example(spanish: "Descargué la aplicación en mi teléfono.", english: "I downloaded the app on my phone."),
        "detallar":     Example(spanish: "Detalla los pasos del proceso.", english: "Detail the steps of the process."),
        "conservar":    Example(spanish: "Conserva los alimentos en el refrigerador.", english: "Keep food in the refrigerator."),
        "desconocer":   Example(spanish: "Desconocía esa información.", english: "I was not aware of that information."),
        "respetar":     Example(spanish: "Respeta las opiniones de los demás.", english: "Respect other people's opinions."),
        "ajustar":      Example(spanish: "Ajusta el asiento antes de conducir.", english: "Adjust the seat before driving."),
        "investigar":   Example(spanish: "Investigo el tema para el ensayo.", english: "I am researching the topic for the essay."),
        "derivar":      Example(spanish: "Esta palabra deriva del latín.", english: "This word derives from Latin."),
        "advertir":     Example(spanish: "Te advierto que el camino es peligroso.", english: "I warn you that the road is dangerous."),
        "personalizar": Example(spanish: "Personaliza tu perfil en la aplicación.", english: "Personalize your profile in the app."),
        "gestionar":    Example(spanish: "Gestiono mi tiempo con un calendario.", english: "I manage my time with a calendar."),
        "incrementar":  Example(spanish: "El ejercicio incrementa tu energía.", english: "Exercise increases your energy."),
        "rodear":       Example(spanish: "Las montañas rodean la ciudad.", english: "The mountains surround the city."),
        "contemplar":   Example(spanish: "Contemplamos el atardecer en silencio.", english: "We contemplated the sunset in silence."),
        "disminuir":    Example(spanish: "El dolor disminuyó con el medicamento.", english: "The pain decreased with the medication."),
        "cruzar":       Example(spanish: "Cruzamos el puente para llegar al pueblo.", english: "We crossed the bridge to reach the town."),
        "tirar":        Example(spanish: "Tira la basura en el contenedor.", english: "Put the trash in the bin."),
        "dividir":      Example(spanish: "Divide la pizza en ocho partes.", english: "Divide the pizza into eight slices."),
        "coincidir":    Example(spanish: "Coincidimos en el aeropuerto por casualidad.", english: "We ran into each other at the airport by chance."),
        "someter":      Example(spanish: "Sometemos la propuesta a votación.", english: "We submit the proposal to a vote."),
        "caracterizar": Example(spanish: "La amabilidad caracteriza a nuestra gente.", english: "Kindness characterizes our people."),
        "parar":        Example(spanish: "Para el coche antes del semáforo.", english: "Stop the car before the traffic light."),
        "implementar":  Example(spanish: "Implementamos el plan desde el lunes.", english: "We implemented the plan starting Monday."),
        "aclarar":      Example(spanish: "Aclaro mis dudas con el profesor.", english: "I clear up my doubts with the teacher."),
        "salvar":       Example(spanish: "Los bomberos salvaron al niño.", english: "The firefighters saved the child."),
        "grabar":       Example(spanish: "Grabé un video del concierto.", english: "I recorded a video of the concert."),
        "consumir":     Example(spanish: "Consumimos menos energía este mes.", english: "We used less energy this month."),
        "votar":        Example(spanish: "Todos deben votar en las elecciones.", english: "Everyone should vote in the elections."),
        "efectuar":     Example(spanish: "Efectuó el pago por transferencia bancaria.", english: "He made the payment by bank transfer."),
        "fallecer":     Example(spanish: "Mi abuelo falleció en paz.", english: "My grandfather passed away peacefully."),
        "hallar":       Example(spanish: "Hallamos la solución después de horas.", english: "We found the solution after hours."),
        "colaborar":    Example(spanish: "Colaboramos con otras organizaciones.", english: "We collaborate with other organizations."),
        "acordar":      Example(spanish: "Acordamos reunirnos el martes.", english: "We agreed to meet on Tuesday."),
        "admitir":      Example(spanish: "Admitió que estaba equivocado.", english: "He admitted he was wrong."),
        "rechazar":     Example(spanish: "Rechacé la oferta de trabajo.", english: "I turned down the job offer."),
        "orientar":     Example(spanish: "El guía nos orientó por la ciudad.", english: "The guide directed us through the city."),
        "montar":       Example(spanish: "Monto en bicicleta los fines de semana.", english: "I ride my bike on weekends."),
        "convocar":     Example(spanish: "Convocaron una reunión de urgencia.", english: "They called an emergency meeting."),
        "sugerir":      Example(spanish: "Te sugiero probar el ceviche.", english: "I suggest you try the ceviche."),
        "dudar":        Example(spanish: "Dudé antes de tomar la decisión.", english: "I hesitated before making the decision."),
        "durar":        Example(spanish: "La película dura dos horas.", english: "The movie lasts two hours."),
        "involucrar":   Example(spanish: "Involucra a toda la familia en el proyecto.", english: "Involve the whole family in the project."),
        "llenar":       Example(spanish: "Llena el vaso con agua fría.", english: "Fill the glass with cold water."),
        "cometer":      Example(spanish: "Cometí un error en el examen.", english: "I made a mistake on the exam."),
        "pintar":       Example(spanish: "Pintamos las paredes de azul.", english: "We painted the walls blue."),
        "oír":          Example(spanish: "Oigo música desde mi cuarto.", english: "I can hear music from my room."),
        "acusar":       Example(spanish: "Lo acusaron de robar el dinero.", english: "They accused him of stealing the money."),
        "nombrar":      Example(spanish: "Nombraron a una mujer como directora.", english: "They appointed a woman as director."),
        "sonar":        Example(spanish: "Suena el despertador a las siete.", english: "The alarm goes off at seven."),
        "alejar":       Example(spanish: "Me alejo del trabajo durante las vacaciones.", english: "I disconnect from work during vacation."),
        "cantar":       Example(spanish: "Canta muy bien en el coro.", english: "She sings very well in the choir."),
        "satisfacer":   Example(spanish: "Este trabajo me satisface mucho.", english: "This job satisfies me a great deal."),
        "favorecer":    Example(spanish: "El clima favorece los cultivos en esta región.", english: "The climate favors crops in this region."),
        "optar":        Example(spanish: "Opté por quedarme en casa.", english: "I chose to stay home."),
        "beneficiar":   Example(spanish: "El nuevo parque beneficia a todo el barrio.", english: "The new park benefits the whole neighborhood."),
        "casar":        Example(spanish: "Se casaron en una pequeña ceremonia.", english: "They got married in a small ceremony."),
        "apreciar":     Example(spanish: "Aprecio mucho tu ayuda.", english: "I really appreciate your help."),
        "reservar":     Example(spanish: "Reservé una mesa para dos personas.", english: "I reserved a table for two people."),
        "acumular":     Example(spanish: "Acumulé muchos libros este año.", english: "I accumulated a lot of books this year."),
        "atacar":       Example(spanish: "El virus ataca el sistema inmune.", english: "The virus attacks the immune system."),
        "confiar":      Example(spanish: "Confío en mi equipo completamente.", english: "I completely trust my team."),
        "autorizar":    Example(spanish: "El jefe autorizó el viaje de trabajo.", english: "The boss authorized the work trip."),
        "convencer":    Example(spanish: "Me convenció de probar el nuevo restaurante.", english: "She convinced me to try the new restaurant."),
        "reclamar":     Example(spanish: "Reclamé mi equipaje en el aeropuerto.", english: "I claimed my luggage at the airport."),
        "regular":      Example(spanish: "La ley regula el uso de esa sustancia.", english: "The law regulates the use of that substance."),
        "inspirar":     Example(spanish: "Su historia inspira a muchas personas.", english: "His story inspires many people."),
        "escoger":      Example(spanish: "Escoge el regalo que más te guste.", english: "Choose the gift you like the most."),
        "reforzar":     Example(spanish: "Reforzamos los conocimientos con práctica.", english: "We reinforce knowledge through practice."),
        "lucir":        Example(spanish: "Luces muy bien con ese vestido.", english: "You look great in that dress."),
        "adelantar":    Example(spanish: "Adelanté el trabajo para tener tiempo libre.", english: "I got ahead on the work to have free time."),
        "fundar":       Example(spanish: "Fundaron la empresa hace veinte años.", english: "They founded the company twenty years ago."),
        "coger":        Example(spanish: "Coge el autobús en la próxima parada.", english: "Take the bus at the next stop."),
        "distribuir":   Example(spanish: "Distribuimos los folletos por la ciudad.", english: "We distributed the flyers around the city."),
        "saltar":       Example(spanish: "Los niños saltan en el parque.", english: "The children jump around in the park."),
        "intervenir":   Example(spanish: "Intervino para calmar la situación.", english: "He stepped in to calm the situation."),
        "enfocar":      Example(spanish: "Enfoca tu energía en lo importante.", english: "Focus your energy on what matters."),
        "fortalecer":   Example(spanish: "El deporte fortalece los músculos.", english: "Sport strengthens the muscles."),
        "liberar":      Example(spanish: "Liberaron a los animales al bosque.", english: "They released the animals into the forest."),
        "vencer":       Example(spanish: "Vencimos al equipo contrario.", english: "We defeated the opposing team."),
        "destruir":     Example(spanish: "El fuego destruyó parte del bosque.", english: "The fire destroyed part of the forest."),
        "calificar":    Example(spanish: "El profesor calificó los exámenes.", english: "The teacher graded the exams."),
        "justificar":   Example(spanish: "Justifica tu respuesta con ejemplos.", english: "Justify your answer with examples."),
        "percibir":     Example(spanish: "Percibo un cambio en su actitud.", english: "I notice a change in his attitude."),
        "parir":        Example(spanish: "La gata parió cuatro gatitos.", english: "The cat gave birth to four kittens."),
        "clasificar":   Example(spanish: "Clasificamos los libros por tema.", english: "We sorted the books by topic."),
        "devolver":     Example(spanish: "Devuelvo los libros a la biblioteca.", english: "I return the books to the library."),
        "resaltar":     Example(spanish: "Resalta las ideas principales del texto.", english: "Highlight the main ideas in the text."),
        "apostar":      Example(spanish: "Apuesto a que va a llover.", english: "I bet it is going to rain."),
        "concentrar":   Example(spanish: "Me concentro mejor en silencio.", english: "I concentrate better in silence."),
        "activar":      Example(spanish: "Activa el modo silencio en el cine.", english: "Activate silent mode at the cinema."),
        "mezclar":      Example(spanish: "Mezcla los ingredientes en un tazón.", english: "Mix the ingredients in a bowl."),
        "precisar":     Example(spanish: "Precisamos más información para decidir.", english: "We need more information to decide."),
        "criticar":     Example(spanish: "Critica de forma constructiva.", english: "Criticize in a constructive way."),
        "prohibir":     Example(spanish: "Está prohibido fumar en este lugar.", english: "Smoking is prohibited in this place."),
        "insistir":     Example(spanish: "Insiste en practicar todos los días.", english: "He insists on practicing every day."),
        "contactar":    Example(spanish: "Contáctame si necesitas ayuda.", english: "Contact me if you need help."),
        "calcular":     Example(spanish: "Calculé el costo total del viaje.", english: "I calculated the total cost of the trip."),
        "reportar":     Example(spanish: "Reportó el problema al supervisor.", english: "She reported the problem to the supervisor."),
        "traducir":     Example(spanish: "Traduzco documentos del inglés al español.", english: "I translate documents from English to Spanish."),
        "renovar":      Example(spanish: "Renovamos el contrato por un año más.", english: "We renewed the contract for another year."),
        "ahorrar":      Example(spanish: "Ahorro dinero para las vacaciones.", english: "I save money for the holidays."),
        "liderar":      Example(spanish: "Lidera el equipo con mucho entusiasmo.", english: "She leads the team with great enthusiasm."),
        "robar":        Example(spanish: "Le robaron la cartera en el bus.", english: "His wallet was stolen on the bus."),
        "disputar":     Example(spanish: "Los equipos disputan la final mañana.", english: "The teams play the final tomorrow."),
        "limpiar":      Example(spanish: "Limpio la casa los sábados.", english: "I clean the house on Saturdays."),
        "editar":       Example(spanish: "Editó el video antes de publicarlo.", english: "She edited the video before publishing it."),
        "titular":      Example(spanish: "Tituló su obra de arte con una sola palabra.", english: "She titled her artwork with a single word."),
        "resumir":      Example(spanish: "Résumé las ideas principales del libro.", english: "Summarize the main ideas of the book."),
        "asignar":      Example(spanish: "Asignaron tareas a cada miembro del equipo.", english: "They assigned tasks to each team member."),
        "despertar":    Example(spanish: "Me despierto con el sonido de los pájaros.", english: "I wake up to the sound of birds."),
        "escapar":      Example(spanish: "Escapamos de la lluvia en una cafetería.", english: "We escaped the rain in a café."),
        "conceder":     Example(spanish: "Le concedieron el permiso para viajar.", english: "They granted him permission to travel."),
        "pegar":        Example(spanish: "Pega la foto en tu cuaderno.", english: "Stick the photo in your notebook."),
        "sustituir":    Example(spanish: "Sustituye el azúcar por miel.", english: "Substitute sugar with honey."),
        "atraer":       Example(spanish: "Esta ciudad atrae a muchos turistas.", english: "This city attracts many tourists."),
        "tender":       Example(spanish: "Tiendo la ropa después de lavarla.", english: "I hang the laundry after washing it."),
        "esconder":     Example(spanish: "El gato se esconde debajo de la cama.", english: "The cat hides under the bed."),
        "circular":     Example(spanish: "El tren circula cada media hora.", english: "The train runs every half hour."),
        "solucionar":   Example(spanish: "Solucionamos el problema rápidamente.", english: "We solved the problem quickly."),
        "estrenar":     Example(spanish: "Estrenamos la película este viernes.", english: "We are premiering the film this Friday."),
        "prometer":     Example(spanish: "Prometió llamarme cuando llegara.", english: "He promised to call me when he arrived."),
        "fomentar":     Example(spanish: "Fomentamos la lectura entre los niños.", english: "We encourage reading among children."),
        "arrancar":     Example(spanish: "El coche no arrancó esta mañana.", english: "The car did not start this morning."),
        "localizar":    Example(spanish: "Localicé el restaurante en el mapa.", english: "I located the restaurant on the map."),
        "tardar":       Example(spanish: "El médico tardó media hora en atenderme.", english: "The doctor took half an hour to see me."),
        "atravesar":    Example(spanish: "Atravesamos el desierto en autobús.", english: "We crossed the desert by bus."),
        "distinguir":   Example(spanish: "Distingo fácilmente los dos dialectos.", english: "I easily distinguish between the two dialects."),
        "oponer":       Example(spanish: "Se oponen al cambio de horario.", english: "They oppose the schedule change."),
        "alimentar":    Example(spanish: "Alimento a mi perro dos veces al día.", english: "I feed my dog twice a day."),
        "constar":      Example(spanish: "El informe consta de diez páginas.", english: "The report consists of ten pages."),
        "explorar":     Example(spanish: "Exploramos rutas nuevas en la montaña.", english: "We explore new routes in the mountains."),
        "prevenir":     Example(spanish: "Es mejor prevenir que curar.", english: "It is better to prevent than to cure."),
        "discutir":     Example(spanish: "Discutimos el tema con calma.", english: "We discussed the topic calmly."),
        "verificar":    Example(spanish: "Verifica la información antes de publicarla.", english: "Verify the information before publishing it."),
        "consolidar":   Example(spanish: "Consolidamos nuestra posición en el mercado.", english: "We consolidated our position in the market."),
        "figurar":      Example(spanish: "Su nombre figura en la lista de ganadores.", english: "His name appears on the list of winners."),
        "gastar":       Example(spanish: "Gasto demasiado en cafés por la mañana.", english: "I spend too much on coffee in the morning."),
        "condenar":     Example(spanish: "El juez condenó al culpable.", english: "The judge sentenced the guilty party."),
        "suceder":      Example(spanish: "¿Qué sucedió en la reunión?", english: "What happened at the meeting?"),
    ]
}

extension Verb {
    var exampleSentence: VerbExamples.Example? {
        VerbExamples.sentences[id]
    }
}
